### ISSUE TITLE
java.lang.OutOfMemoryError: pthread_create (stack size 16384 bytes) failed: Try again

### ISSUE THREAD

**Issue by ecgreb** [mapzen/open#181]
``` bash
java.lang.OutOfMemoryError: pthread_create (stack size 16384 bytes) failed: Try again
at java.lang.VMThread.create(Native Method)
at java.lang.Thread.start(Thread.java:1029)
at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:920)
at java.util.concurrent.ThreadPoolExecutor.processWorkerExit(ThreadPoolExecutor.java:988)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
at java.lang.Thread.run(Thread.java:841)

```

**Comment by shawnChai** [comment]
have you resolved?

**Comment by sarahlensing** [comment]
Active development on this project has ended. Please see Eraser Map instead (https://github.com/mapzen/eraser-map). Sorry for any inconvenience this causes.
