### ISSUE TITLE
org.json.JSONException: End of input at character 0 of

### ISSUE THREAD

**Issue by ecgreb** [mapzen/open#193]
``` bash
org.json.JSONException: End of input at character 0 of 
at org.json.JSONTokener.syntaxError(JSONTokener.java:450)
at org.json.JSONTokener.nextValue(JSONTokener.java:97)
at org.json.JSONObject.<init>(JSONObject.java:155)
at org.json.JSONObject.<init>(JSONObject.java:172)
at com.mapzen.osrm.Route.<init>(Route.java:33)
at com.mapzen.osrm.Router.run(Router.java:124)
at java.lang.Thread.run(Thread.java:841)

```

**Comment by 401885064** [comment]
I met the same problem.  do you have work?
